name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build back-end-spring
      run: cd ./back-end ; mvn package
    - name: Build the Docker image
      run: docker build ./back-end --file ./back-end/Dockerfile --tag back-end:$(date +%s)
